### ISSUE TITLE
How to downgrade ?

### ISSUE THREAD

**Issue by bbaranoff** [notzheng/pallas-proxy#1]
Hello, seems very interesting stuff can it be used to downgrade firmware, and how ?
I tried with 
```
idevicerestore -s http://pallas-proxy.notzheng.com/v2/assets -e ...ipsw
```
or 
```
go run .
idevicerestore -s http://127.0.0.1/v2/assets -e ...ipsw
```
and both returned me
bad gateway 406
if i use ideviceactivate then i have
Failed to get ActivationInfo from mobileactivation

**Comment by notzheng** [comment]
I apologize for the inconvenience. As shown in the code, this is just a simple reverse proxy that performs base64 decoding on the content returned by Apple's servers.
